apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: my-app
  name: my-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  strategy: {}

  template:
    metadata:
      labels:
        app: my-app

    spec:
      containers:
      - image: my-app-image
        name: my-app-image
        imagePullPolicy: IfNotPresent
        resources: {}

status: {}
