apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: my-static-app-deployment
  name: my-static-app-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-static-app-deployment

  template:
    metadata:
      labels:
        app: my-static-app-deployment

    spec:
      containers:
        - image: nginx:1.31
          name: my-static-app-name
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: static-files-volume

      volumes:
        - name: static-files-volume
          configMap:
            name: static-files-cm

---
apiVersion: v1
kind: Service

metadata:
  name: my-static-app-svc

spec:
  type: NodePort
  selector:
    app: my-static-app-deployment
  ports:
    - port: 80  # Port exposed within the cluster
      targetPort: 80  # Port on the pods

---
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: my-static-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  # TODO: Nginx ingress is deprecated IIRC, I should try Traefik
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-static-app-svc
                port:
                  number: 80
